### ISSUE TITLE
General query 

### ISSUE THREAD

**Issue by pythonpanda2** [benjaminbolling/DynaGUI#4]
@benjaminbolling 

It seems that the package has a strong dependency on  PyTango . How widely  is this package used in the domain addressed in this article ? Would you envision using the DynaGUI package in application where  PyTango packages  are not used ?

**Comment by benjaminbolling** [comment]
In order to decrease the dependency of PyTango. All codes now enables user to select between the packages "Tango" (using PyTango), "EPICS" (using PyEPICS), "Finance" (using Pandas Datareader) and "Randomizer" (for testing and demonstration purposes using random values). Other packages used for obtaining values from various data polling sources can be added in later stages with ease. @pythonpanda2 : Since you opened this issue, I leave it up to you to decide if this issue is to be considered as closed or not.

**Comment by benjaminbolling** [comment]
As for how much PyTango is used: "The TANGO control system is a free open source device-oriented controls toolkit for controlling any kind of hardware or software and building SCADA systems" (from TANGO wikipedia page), and PyTango is a package used in Python for communicating with the TANGO control system.

EPICS (Experimental Physics and Industrial Control System) is used at some other facilities (one of which I am working at), and hence, pyEPICS is used in the Python package to communicate with this control system.

In order to demonstrate the openness of the DynaGUI package, the two additional 'data analysis' packages "Finance" and "Random" were added.

**Comment by pythonpanda2** [comment]
Thanks a lot for the explanation. I can clearly see some of the explanation in requirements. So i will close the issue and add further comments in the requirements issue.
